### ISSUE TITLE
ld_func='interp' results in nans for fluxes when out of range

### ISSUE THREAD

**Issue by bpablo** [phoebe-project/phoebe2#60] opened 2016-08-31 19:30 UTC
The following code  has 2 issues and I don't think it should.

1.) Warning: Root polishing did not succeed
2.) nans returned for several of the flux elements
*Note: I have increased the binary period up to 100 days and nans are still produced.

`import phoebe`
`import numpy as np`
`b = phoebe.Bundle.default_binary()`
 `b['ecc']=0.4`
 `b['period@orbit']=30.0`
 `b.add_dataset('LC', time=np.linspace(0,30, 10))`
 `b.run_compute()`

**Comment by kecnry** [comment] 2016-08-31 19:52
the nans are coming from the 'interp' limb-darkening... possibly because your teffs or loggs are going out of range?

@aprsa is this the expected behavior, or is there a warning or error we can throw instead of returning nans?

For now you can (mostly) get around this by setting ld_func and ld_func_bol to something else (ie 'logarithmic')

**Comment by kecnry** [comment] 2016-08-31 19:59
@horvatm - as for the root polishing warning, would it help if I expose and report (perhaps in a separate issue) the roche parameters (q, F, d, Omega) whenever this happens?

**Comment by horvatm** [comment] 2016-08-31 20:03
@kecnry Yes, it would help if you could give me (q,F,d, Omega) and which libphoebe routine reports this warnings.

**Comment by horvatm** [comment] 2016-08-31 20:04
Perhaps connected to this: We always calculate critical potential in all Lagrange points, but rarely we use Omega(L3). I have already prepared C++ routine to more selectively calculate potentials. Should I port this?

**Comment by kecnry** [comment] 2016-08-31 20:15
let's see - if its often the L3 critical potential that is triggering this warning, then that might be worth it.

But I'm quite certain the nans are unrelated to this warning message, so let's try to track down what roche parameters cause the warning and deal with those in this issue: https://github.com/phoebe-project/phoebe2/issues/61

**Comment by bpablo** [comment] 2016-08-31 20:44
@kecnry ...It's the default binary and the components are exactly the same.  If it was out of range for some reason, wouldn't that be an issue running a normal run_compute? I don't see how ecc or the period would affect these things.

**Comment by kecnry** [comment] 2016-08-31 20:50
@bpablo volume conservation will cause a change in loggs (and therefore teffs) as a function of time.

**Comment by aprsa** [comment] 2016-08-31 21:30
nans are a result of the out-of-bounds situation for LD interpolation. We /could/ allow extrapolation, but I don't think we want to do that. Whenever nans are returned, we should throw an error that the models are not suitable for the system at hand.

To work around this, @bpablo should change the parameters to a reasonable logg/Teff/[M/H] range. Everything should be fine then.

**Comment by bpablo** [comment] 2016-09-01 02:07
@aprsa I'm not what sure what is considered reasonable, but hopefully the sun counts. 2 identical suns in a 30 day orbit and no eccentricity. Still get nans.
`b = phoebe.Bundle.default_binary()`
`b.add_dataset('LC', time = np.linspace(0,30.0, 10.))`
`b.flip_constraint(solve_for='sma', constraint_func='mass', component='primary')`
`b.flip_constraint(solve_for='sma', constraint_func='mass', component='secondary')`
`b['mass@primary'] = 1.0`
`b['mass@secondary'] = 1.0`
`b['teff@primary'] = 5777.0`
`b['teff@secondary'] = 5777.0`
`b['period@binary'] = 30.0`
`b.run_compute(label='detailed')`

**Comment by kecnry** [comment] 2016-09-01 14:19
Implemented error message in https://github.com/phoebe-project/phoebe2/commit/e972cd33f7b259f8b7081063bb3a81259fde62bc

Whenever ld_func='interp' results in any nans for intensities, we now raise the following error:
"ValueError: interpolation out of bounds - try setting reasonable system parameters or changing ld_func to something other than 'interp'"

Note:
* I would like to be able to predict this in advance of running compute, but that's not at all trivial, especially for the case of eccentric orbits.  If anyone has any ideas, I'm all ears.

* We may also need to revisit this when we get around to implementing fitting - raise an error will not be nice at all for cost functions.

Does this close the issue then or are there still concerns about the actual bounds of the interpolation itself?

**Comment by bpablo** [comment] 2016-09-01 17:24
@kecnry I'm still not convinced. I haven't found a system yet that is not out of bounds. Did you run the system above with two solar like stars? Do you agree that it shouldn't give nans? If this is in fact out of bounds I need to know why, because I don't think it should be.

**Comment by bpablo** [comment] 2016-09-01 17:36
@kecnry @aprsa My suggestion for the time being is to change the default from interp. It seems to have very narrow parameters currently for which it is applicable. I have a feeling this opinion won't be popular, but I feel that the default should work for two solar like stars in a long period non eccentric binary.

**Comment by giammarc** [comment] 2016-09-01 17:48
I don't know if this is helpful.  I ran into this also today, using a 
script that ran in the past without issue.  It wouldn't go past the 
run_compute().  Changing ld_func to 'linear' gave a different error (is 
that to be expected?).  Changing to logarithmic worked.

**Comment by aprsa** [comment] 2016-09-01 19:05
I managed to reproduce and I traced the problem down to falling off the left edge of mu (i.e. mu < 0.001). Fixing now.

**Comment by aprsa** [comment] 2016-09-01 20:39
I will close this issue with an understanding that root polishing will be addressed elsewhere.

**Closed by aprsa** 2016-09-01 20:39 UTC
Labels: bug
