### ISSUE TITLE
passband problem

### ISSUE THREAD

**Issue by AstroJLin** [phoebe-project/phoebe2#585] opened 2022-04-30 20:50 UTC
Hi, 

Here, I try to use passband='Johnson:R' and passband='Johnson:B', it threw an error.  However, when I use passband='Johnson:V', it can work.

Can you tell me the reason for this error?

The  code:
b.add_dataset(kind='lc', times=timesR, fluxes=fluxesR,sigmas=sigmasR_lc,passband='Johnson:R')   
b.add_dataset(kind='lc', times=timesB, fluxes=fluxesB,sigmas=sigmasB_lc,passband='Johnson:B')
Thanks

The error is as follows:

###########
￼ File "/home/jlin/PHOEB/SPOT.py", line 140, in
b.run_compute(model='distortion_method_none')
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/parameters/parameters.py", line 401, in _send_if_client
return fctn(self, *args, **kwargs)
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/frontend/bundle.py", line 10282, in run_compute
model, computes, datasets, do_create_fig_params, changed_params, overwrite_ps, kwargs = self._prepare_compute(compute, model, dataset, **kwargs)
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/frontend/bundle.py", line 9977, in _prepare_compute
report = self.run_checks_compute(compute=computes, allow_skip_constraints=False,
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/frontend/bundle.py", line 3485, in run_checks_compute
elif conf.update_passband_ignore_version or _timestamp_to_dt(installed_timestamp) == _timestamp_to_dt(online_timestamp):
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/atmospheres/passbands.py", line 2938, in _timestamp_to_dt
return datetime.strptime(timestamp, "%a %b %d %H:%M:%S %Y")
File "/home/jlin/anaconda3/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
File "/home/jlin/anaconda3/lib/python3.8/_strptime.py", line 349, in _strptime
raise ValueError("time data %r does not match format %r" %

builtins.ValueError: time data 'Wed Jan 22 15:53:39 2020' does not match format '%a %b %d %H:%M:%S %Y'

###############

**Comment by AstroJLin** [comment] 2022-04-30 21:00
Hi, 
My apologizes. The PDF the file doesn't seem to open.

Here the error is as follows:

###########
￼ File "/home/jlin/PHOEB/SPOT.py", line 140, in <module>
  b.run_compute(model='distortion_method_none')
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/parameters/parameters.py", line 401, in _send_if_client
  return fctn(self, *args, **kwargs)
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/frontend/bundle.py", line 10282, in run_compute
  model, computes, datasets, do_create_fig_params, changed_params, overwrite_ps, kwargs = self._prepare_compute(compute, model, dataset, **kwargs)
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/frontend/bundle.py", line 9977, in _prepare_compute
  report = self.run_checks_compute(compute=computes, allow_skip_constraints=False,
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/frontend/bundle.py", line 3485, in run_checks_compute
  elif conf.update_passband_ignore_version or _timestamp_to_dt(installed_timestamp) == _timestamp_to_dt(online_timestamp):
File "/home/jlin/anaconda3/lib/python3.8/site-packages/phoebe/atmospheres/passbands.py", line 2938, in _timestamp_to_dt
  return datetime.strptime(timestamp, "%a %b %d %H:%M:%S %Y")
File "/home/jlin/anaconda3/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
  tt, fraction, gmtoff_fraction = _strptime(data_string, format)
File "/home/jlin/anaconda3/lib/python3.8/_strptime.py", line 349, in _strptime
  raise ValueError("time data %r does not match format %r" %

builtins.ValueError: time data 'Wed Jan 22 15:53:39 2020' does not match format '%a %b %d %H:%M:%S %Y'

###############

**Comment by kecnry** [comment] 2022-05-01 00:21
What version of PHOEBE are you using?  A similar error was fixed in [2.3.19](https://github.com/phoebe-project/phoebe2/pull/411), but it looks from your traceback like this might be triggering a similar issue with the system parsing of datetime strings, but in a different place in PHOEBE from that original fix.

Assuming you're using the latest release, I can try to get a similar bugfix out for this.  Would you be willing to test from a prerelease branch to see if it fixes your issue (since this is system-dependent and so we have no way of reproducing the error on our end)?

You also might be able to get around the issue by manually forcing phoebe to re-download the passbands.  You can call `phoebe.update_passband('Johnson:B'); phoebe.update_passband('Johnson:R')` (if you installed phoebe globally with sudo, you may need to do this within sudo as well).

**Comment by AstroJLin** [comment] 2022-05-01 19:13
Hi Kecnry,

I am running version 2.3.51 of phoebe. Today, I have update a version  2.3.51 to  the latest release. However, I still encounter the error.

I think I gold to use a prerelease branch to see if it fixes my issue. In addition, you mentioned that I am able to get around the issue by manually forcing phoebe to re-download the passbands. Here, I have some doubts. Could you provide me more information (Input instruction ) in detail for how to manually force phoebe to re-download the passbands.


Thanks!

**Comment by kecnry** [comment] 2022-05-01 20:35
Can you please try the proposed bugfix and let me know whether that seems to work on your machine (no need to try to force re-downloading passbands).

You can either checkout the branch from github and build manually, or install directly from pip (something like `pip install git+https://github.com/phoebe-project/phoebe2.git@bugfix-passband-timestamp` - checking the version should then show 2.3.60 even though that is not officially released yet).

Thanks!
Kyle

**Comment by AstroJLin** [comment] 2022-05-03 20:16
Hi Kyle,

I try to use pip (pip install git+https://github.com/phoebe-project/phoebe2.git@bugfix-passband-timestamp)  to install the proposed bugfix. However, I can not install the proposed bugfix using the pip.  Can you provide another way?

Thanks!
The error is as follow:
#####
Collecting git+https://github.com/phoebe-project/phoebe2.git@bugfix-passband-timestamp
 Cloning https://github.com/phoebe-project/phoebe2.git (to revision bugfix-passband-timestamp) to /tmp/pip-req-build-iz63qabo
 Running command git clone --filter=blob:none -q https://github.com/phoebe-project/phoebe2.git /tmp/pip-req-build-iz63qabo
 Running command git checkout -b bugfix-passband-timestamp --track origin/bugfix-passband-timestamp
 fatal: unable to access 'https://github.com/phoebe-project/phoebe2.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
######

**Comment by kecnry** [comment] 2022-05-03 22:56
Hmmm, seems like a network redirect issue.  Can you try with http instead of https?

**Comment by AstroJLin** [comment] 2022-05-05 12:43
Hi Kyle,

I have tried with http instead of https, but I still encounter a network redirect issue.

In addition, I want to use my model to fit multi-band data (BVR).  Here, I only able to fit respectively the single band using my model including to determine uncertainties with emcee.  However, I want to know how to set up the parameters to make my model  to fit multi-band data (BVR)  together including to determine uncertainties with emcee.  Can you give me some suggestions. 

Thanks!

**Comment by kecnry** [comment] 2022-05-05 13:01
Ok, I'll have to see if I can test some other way and if not will just release and cross our fingers that it fixes the issue!  I'll update you here when that is done (hopefully in the next few days).

> In addition, I want to use my model to fit multi-band data (BVR). Here, I only able to fit respectively the single band using my model including to determine uncertainties with emcee. However, I want to know how to set up the parameters to make my model to fit multi-band data (BVR) together including to determine uncertainties with emcee. Can you give me some suggestions.

Assuming your photometry is properly calibrated, you want `pblum_mode='dataset-coupled'` for all but one of your passbands.  That is briefly explained in the [pblum_mode tutorial](http://phoebe-project.org/docs/latest/tutorials/pblum).  If that doesn't help or doesn't do what you need, please open a new issue or discussion thread so it doesn't get lost in this bug report.

Thanks!

**Closed** 2022-05-06 00:04 UTC
Labels: bug

**Comment by kecnry** [comment] 2022-05-06 00:06
I released the fix as 2.3.60.  If that does not do the trick for your case, please feel free to re-open the issue and we can try to find another fix.  Thanks!

**Comment by AstroJLin** [comment] 2022-05-08 09:35
Hi Kyle,

I have updated a version to the latest release and the latest version have fixed the issue!

Thanks!
