### ISSUE TITLE
Spurious first flux value

### ISSUE THREAD

**Issue by danhey** [phoebe-project/phoebe2#358] opened 2019-11-28 00:12 UTC
**Problem description**

In some systems the first flux point can be totally disconnected from the rest of the light curve.
![example](https://user-images.githubusercontent.com/38233719/69767218-3d7b5880-1149-11ea-8163-c18b0596c5f5.png)
This happens for blackbody or ck2004 atms.

**Example**
```python
b = phoebe.default_binary()

phases = np.linspace(-0.5,0.5,200)
b = phoebe.default_binary()
b.add_dataset('lc', compute_phases=phases)

b['pblum_mode'] = 'pbflux'
b['teff@primary'] = 17512.569277007777
b['teff@secondary'] = 5836.180072011337
b['gravb_bol@primary'] = 0.9
b['irrad_frac_refl_bol@primary'] = 1.
b['q'] = 0.9736344516974118
b['requiv@primary'] = 1.536400786022977
b['requiv@secondary'] = 0.7123388445305453
b['teff@secondary'] = 5836.180072011337
b['incl@binary'] = 74.5962754314255
b['ecc'] = 0.033193127594812404
b['per0'] = 46.14228713978144

b.run_compute()
fluxes = b['value@fluxes@model']
```

**Environment**
devel branch

**Comment by kecnry** [comment] 2019-11-28 00:19
See also #341 - apparently this wasn't fully fixed after all

**Comment by danhey** [comment] 2019-12-06 22:23
I've looked into this a bit closer and it disappears when the irrad method is set to None, i.e.
```python
b.run_compute(irrad_method='none', ntriangles=700, model='refl_false')
```

**Comment by kecnry** [comment] 2019-12-06 23:15
I cannot reproduce in the latest in development on my machine.

Note: pbflux hasn't been supported in a while on the devel branch, so I commented that line out, but I don't expect that to affect this... unless there is any chance you happen to be running on a version of the code before 2.1.16 was merged into development?  If so, can you try running on the latest version?

**Comment by kecnry** [comment] 2019-12-22 15:20
If anyone runs into something like this in 2.2 or devel again feel free to re-open the issue, but I believe this should be fixed now.

**Closed by kecnry** 2019-12-22 15:20 UTC
